### PR TITLE
Fontconfig is good to go

### PR DESCRIPTION
**Pull request by uilianries**
Hi!

This PR is the continuation of fontconfig package. 

We could promote it to Conan Center, but it has some non-official dependencies from Bincrafters.

### CODE REVIEW

**Comment by SSE4** [comment]
@uilianries 
what's wrong with appveyor set-up?
```
Build started
git clone -q --branch=testing/2.13.1 https://github.com/conan-community/conan-fontconfig.git C:\projects\conan-fontconfig
git checkout -qf 74169319f26db13933fa0c1fd9872b6e2d76e485
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```
https://ci.appveyor.com/project/ConanCIintegration/conan-fontconfig/builds/22326411
also, do you think having dependencies not in conan-center should prevent package itself from inclusion?

**Comment by uilianries** [comment]
Actually fontconfig has no support for Windows, so I didn't put the appveyor file here. I have an alias to run bincrafters-envy and it created an Appveyor project for this project. Maybe I should try building fontconfig with mingw before to remove the appveyor project.

**Comment by SSE4** [comment]
okay, let's merge and disable appveyor for now then

**Comment by uilianries** [comment]
All requirements have Windows supported, I just checked it now. I gonna open a new PR with Windows support, let's see if it works.

**Pull request merged**
