### PR TITLE
Fix debug builds and add CI for gcc 9 and clang 8

### PR DESCRIPTION
**Pull request by cqjjjzr**
Hi.

In commit  43e6f058612a7b433e1da02556277c2d33d626e3 code below was added:

```python
        if self.settings.build_type == "Debug":
            tools.replace_in_file("freetype2.pc", "-lfreetype", "-lfreetyped")
```

which will broke if the pkg-config file already contains "-lfreetyped", changing it into "-lfreetypedd"(https://travis-ci.com/cqjjjzr/conan-libass/jobs/231041120). So we should use regexp to check such situation.

also, I found that gcc9 and clang8 are not in Travis CI config, so I append them into it.

### CODE REVIEW

**Comment by cqjjjzr** [comment]
I noticed most of conan-community recipes has no GCC9 and Clang8 builds. Maybe we need to fix this.

**Comment by Croydon** [comment]
@cqjjjzr Recipes will be migrated step by step to https://github.com/conan-io/conan-center-index/

There, new compilers will be added globally

**Comment by SSE4** [comment]
it fails right now because of expat

**Comment by cqjjjzr** [comment]
@SSE4 that's because Expat don't have a prebuilt artifact from GCC9 and clang8.

Need I revert the commit appending the gcc9?

**Comment by SSE4** [comment]
@cqjjjzr feel free to submit PR to the conan-center-index. we encourage other users to try new system and share feedback.

**Comment by Croydon** [comment]
Expat is now in CCI

@cqjjjzr I suggest you change it the dependency to `expat/2.2.7` and we could merge this for now

**Comment by cqjjjzr** [comment]
well, after switching to `expat/2.2.7` all travis cases failed.

**Comment by Croydon** [comment]
Good catch. CCI isn't building 32bit builds anymore, so we need to exclude them from all other recipes as well now

You should be able to do something like this https://github.com/bincrafters/templates/pull/60/files#diff-e3df74656c32c58547217ee44ffbdd84R1

**Comment by cqjjjzr** [comment]
XCode 8.1 dropped as well??

**Comment by Croydon** [comment]
Yes, you can see all supported configurations for prebuilds here: https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations

+ Clang 8 and GCC 9 which are supported, but missing in this wiki post right now

**Pull request merged**
